FROM python:3.9

WORKDIR /app

COPY app/requirements.txt /app//requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY app/main.py /app/

# 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]