default_context:
  project_name: 'projet7'
  project_slug: 'credit'
  domain_main: 'FastAPI'
  domain_staging: 'FastAPI'
  docker_swarm_stack_name_main: 'FastAPI'
  docker_swarm_stack_name_staging: 'FastAPI'
  secret_key: 'd3d746c138dd4976c805bb3f84d7405952cde9927b46437477a31a0d32306dd4'
  first_superuser: 'cecile'
  first_superuser_password: '97bbeaa39d4bf0b4d223cdc30aa58ffc421821420d6a6358a046d4b2e5a2a6ae'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.FastAPI, https://FastAPI, https://FastAPI, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@FastAPI'
  couchbase_user: 'admin'
  couchbase_password: 'changethis'
  couchbase_sync_gateway_cors: 'http://localhost:4984, http://localhost:4985, http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, http://dev.FastAPI, https://FastAPI, https://db.FastAPI, https://FastAPI, https://db.FastAPI, http://local.dockertoolbox.tiangolo.com, http://local.dockertoolbox.tiangolo.com:4984, http://localhost.tiangolo.com, http://localhost.tiangolo.com:4984'
  couchbase_sync_gateway_user: 'sync'
  couchbase_sync_gateway_password: 'changethis'
  traefik_constraint_tag: 'FastAPI'
  traefik_constraint_tag_staging: 'FastAPI'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:97bbeaa39d4bf0b4d223cdc30aa58ffc421821420d6a6358a046d4b2e5a2a6ae'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  docker_image_sync_gateway: 'sync-gateway'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
